// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvWPVWcVXE3aEp6h1EzOuEQiYjzLU2eyo',
    appId: '1:754463672438:web:026a3b43f4021b7b9f3757',
    messagingSenderId: '754463672438',
    projectId: 'telekom-f3eb5',
    authDomain: 'telekom-f3eb5.firebaseapp.com',
    storageBucket: 'telekom-f3eb5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnrmq3LJiSDbnQnbRbjhbi_V7OclOyVoc',
    appId: '1:754463672438:android:5f08f097e53099859f3757',
    messagingSenderId: '754463672438',
    projectId: 'telekom-f3eb5',
    storageBucket: 'telekom-f3eb5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3WSHvXpItKrBxR_sHi9BAg6ECLtkI4JQ',
    appId: '1:754463672438:ios:55ab552966cfdeda9f3757',
    messagingSenderId: '754463672438',
    projectId: 'telekom-f3eb5',
    storageBucket: 'telekom-f3eb5.appspot.com',
    iosBundleId: 'com.example.eventHub',
  );
}
